- name: Install php-fpm & php extensions
  become: true
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
  - php-fpm
  - php-gd
  - php-curl
  - php-mysql
  - php-dom
  - php-xml

- name: Restart php-fpm
  become: yes
  service: name=php7.2-fpm state=restarted
